# Generated by Django 2.0.7 on 2019-06-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190608_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='pic',
            field=models.ImageField(blank='True', default='default.png', upload_to=''),
        ),
    ]
