# Generated by Django 2.0.7 on 2019-06-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_info_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='calci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('costedu', models.IntegerField()),
                ('years', models.IntegerField()),
                ('monthlyinvestm', models.IntegerField()),
            ],
        ),
    ]
