# Generated by Django 2.0.7 on 2019-06-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_calci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
