# Generated by Django 2.0.7 on 2019-06-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_info_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='calci',
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
