# Generated by Django 2.0.7 on 2019-06-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190610_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='info',
            name='pic',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
