# Generated by Django 2.0.7 on 2019-06-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20190612_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
